// <auto-generated />
using System;
using CodeInsight.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CodeInsight.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CodeInsight.Core.Entities.AnalysisReport", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                b.Property<double>("ComplexityScore").HasColumnType("REAL");
                b.Property<double>("CodeQualityScore").HasColumnType("REAL");
                b.Property<int>("DeepNestingCount").HasColumnType("INTEGER");
                b.Property<int>("DuplicateBlockCount").HasColumnType("INTEGER");
                b.Property<string>("ErrorMessage").HasColumnType("TEXT");
                b.Property<int>("HighComplexityCount").HasColumnType("INTEGER");
                b.Property<int>("LongMethodCount").HasColumnType("INTEGER");
                b.Property<double>("MaintainabilityScore").HasColumnType("REAL");
                b.Property<int>("ProgressPercent").HasColumnType("INTEGER");
                b.Property<int>("RepositoryId").HasColumnType("INTEGER");
                b.Property<DateTime>("StartedAt").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<int>("TotalFilesAnalyzed").HasColumnType("INTEGER");
                b.Property<int>("TotalIssuesFound").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("RepositoryId");
                b.ToTable("AnalysisReports");
            });

            modelBuilder.Entity("CodeInsight.Core.Entities.CodeIssue", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("CodeSnippet").HasMaxLength(2000).HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                b.Property<string>("FileName").IsRequired().HasMaxLength(260).HasColumnType("TEXT");
                b.Property<string>("FilePath").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
                b.Property<string>("IssueType").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<int?>("LineEnd").HasColumnType("INTEGER");
                b.Property<int?>("LineStart").HasColumnType("INTEGER");
                b.Property<int?>("MetricValue").HasColumnType("INTEGER");
                b.Property<string>("MethodName").HasColumnType("TEXT");
                b.Property<int>("ReportId").HasColumnType("INTEGER");
                b.Property<string>("Severity").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<string>("Suggestion").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ReportId");
                b.ToTable("CodeIssues");
            });

            modelBuilder.Entity("CodeInsight.Core.Entities.Repository", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Description").HasColumnType("TEXT");
                b.Property<string>("Language").HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Owner").HasColumnType("TEXT");
                b.Property<int?>("Stars").HasColumnType("INTEGER");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.Property<string>("Url").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Url").IsUnique();
                b.ToTable("Repositories");
            });

            modelBuilder.Entity("CodeInsight.Core.Entities.AnalysisReport", b =>
            {
                b.HasOne("CodeInsight.Core.Entities.Repository", "Repository")
                    .WithMany("Reports").HasForeignKey("RepositoryId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Repository");
            });

            modelBuilder.Entity("CodeInsight.Core.Entities.CodeIssue", b =>
            {
                b.HasOne("CodeInsight.Core.Entities.AnalysisReport", "Report")
                    .WithMany("Issues").HasForeignKey("ReportId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Report");
            });

            modelBuilder.Entity("CodeInsight.Core.Entities.Repository", b => b.Navigation("Reports"));
            modelBuilder.Entity("CodeInsight.Core.Entities.AnalysisReport", b => b.Navigation("Issues"));
#pragma warning restore 612, 618
        }
    }
}
